Feature/refactori18n
udistrital/arka_cliente pull request #575
Opened 2021-03-18 19:29 UTC by CristianDavidSanchez

Implementación de la librería i18n en el modulo de entradas #568

2021-03-18 20:43 UTC, AlexFBP requested changes
Basta con revisar la llave `ActaId` (en/es.json) y su uso en consulta-entrada.component.html

El resto queda a criterio del desarrollador, una vez revisado lo anterior

Una vez realizados los cambios y antes de hacer el commit y push, confirmar si el `ng lint` no salta, típicamente molesta cuando no hay espacios antes/despues de una asignación

2021-03-18 20:43 UTC, AlexFBP commented on src/assets/i18n/en.json
> +      "ActaNo": "Receipt Certificate N°",
Después de traducir se concatena el ID? Esta labor la debe realizar el motor de traducción ([i18n+L10n](https://www.w3.org/International/questions/qa-i18n.es.html)), típicamente mediante interpolación de variables. Particularmente, lo que se coloque entre `{{}}` el motor de traducción lo va a reemplazar por lo que se le pase. Y una frase puede implicar más de una variable

De ser así, preferible usar/modificar la i18n `id_forma1` en vez de `ActaNo`

La razón de que la concatenación la haga el motor de traducción es que en otro(s) idioma(s) el número puede/debe ir en otro lugar de la frase, por lo que se prefiere manejar interpolación de variables, en este caso `{{ID}}`, de tal manera que quien realice la L10n ubique el `{{ID}}` donde sea necesario

Dos ejemplos:
- Traduccion desde el .ts
  https://github.com/udistrital/arka_cliente/blob/1ebfba17288b039e12804d64203fe112f3696ab0/src/app/pages/acta-recibido/verificacion-acta-recibido/verificacion-acta-recibido.component.ts#L374-L384
- Traduccion desde el .html
  https://github.com/udistrital/arka_cliente/blob/803c42afc69d15bd9035e65c42296c8d3baf7497/src/app/pages/entradas/registro/registro.component.html#L24

- Otro ejemplo de traducción desde el .ts:
  https://github.com/udistrital/arka_cliente/blob/1ebfba17288b039e12804d64203fe112f3696ab0/src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts#L898-L914

2021-03-18 20:43 UTC, AlexFBP commented on src/assets/i18n/es.json
> +      "ActaNo": "Acta de Recibido N°",
Mismo comentario que en `en.json`

2021-03-18 20:43 UTC, AlexFBP commented on src/app/pages/entradas/consulta-entrada/consulta-entrada.component.html
> +           : {{ entradaEspecifica.ActaRecibidoId }}</p>
Revisar comentario en `en.json`

2021-03-18 20:43 UTC, AlexFBP commented on src/app/pages/entradas/consulta-entrada/consulta-entrada.component.html
> +           : {{ entradaEspecifica.TipoEntradaId.Nombre }}</p>
Si es posible, usar interpolación - Revisar comentario en `en.json`

2021-03-18 20:43 UTC, AlexFBP commented on src/app/pages/entradas/consulta-entrada/consulta-entrada.component.html
> +          <p class="text-uppercase"><strong>{{'GLOBAL.Placa' | translate }}</strong>: {{Placa}}</p>
Si es posible, usar interpolación - Revisar comentario en `en.json`

2021-03-18 20:43 UTC, AlexFBP commented on src/app/pages/entradas/consulta-entrada/consulta-entrada.component.html
> +            <strong>{{'GLOBAL.observaciones' | translate }}</strong>: {{ entradaEspecifica.Observacion }}
Si es posible, usar interpolación - Revisar comentario en `en.json`

2021-03-23 17:29 UTC, CristianDavidSanchez commented on src/app/pages/entradas/consulta-entrada/consulta-entrada.component.html
> +           : {{ entradaEspecifica.ActaRecibidoId }}</p>
N/A por que estar resuelto en frase se recomienda como está actualmente.

2021-03-23 17:48 UTC, AlexFBP approved these changes

2021-03-23 17:48 UTC, merged