Feature/registro acta
udistrital/arka_cliente pull request #713
Opened 2021-07-23 01:34 UTC by ludwinggsanchez

Closes #645

2021-07-23 02:58 UTC, AlexFBP requested changes
Probar si se puede usar simplemente Date para comparación de fechas

2021-07-23 02:58 UTC, AlexFBP commented on src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
> +              value: Soporte.SoporteActa.FechaSoporte.toString() !== '0001-01-01T00:00:00Z' ?
Para comparaciones de fechas, usar la [API Date](https://developer.mozilla.org/es/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Date), dado que se encarga automáticamente de conversiones horarias y mas...

Por ejemplo, jugando en la consola:
![image](https://user-images.githubusercontent.com/6588872/126731595-b171d96d-468e-45de-88a6-d89613b7b4ba.png)

Si `Soporte.SoporteActa.FechaSoporte` es de tipo `Date` se podría usar directamente para la comparación:
![image](https://user-images.githubusercontent.com/6588872/126731713-cb543893-e7ac-45fd-b4f3-a2dbbdd5f2e5.png)

Para este caso, la "fecha 0" contra la que se compara actualmente, podría ser a efectos prácticos algo como un año antes de la fecha de establecimiento de la U...

2021-07-26 07:13 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
> +              value: Soporte.SoporteActa.FechaSoporte.toString() !== '0001-01-01T00:00:00Z' ?
La validación se hizo necesaria dado el valor 0 de fecha de go. Cuando no se guardaba la fecha de soporte, y luego cuando se hace la consulta de la transacción, el valor que trae es '0001-01-01T00:00:00Z' y al cargar el formulario se ve como sigue:
![image](https://user-images.githubusercontent.com/35748918/126947534-bbe21694-ba82-4aa3-89c9-8ac992f82ad5.png)
Cuando realmente el campo debería estar vacío.
Se cambia la validación de la fecha 0 y se usa el API Date de js

2021-07-26 13:31 UTC, AlexFBP approved these changes

2021-07-26 13:32 UTC, merged