Feature/soportes sin elementos
udistrital/arka_cliente pull request #764
Opened 2021-09-02 03:01 UTC by ludwinggsanchez

Actualización al cliente según udistrital/acta_recibido_crud#60, udistrital/acta_recibido_crud#61 y udistrital/arka_mid#170

2021-09-03 05:26 UTC, AlexFBP reviewed
Comentarios "menores" respecto a la organización de los models, y de extender `Base` para "ahorrar" algunas líneas de código que se repiten en varios lados...

2021-09-03 05:26 UTC, AlexFBP commented on src/app/@core/data/models/acta_recibido/acta_recibido.ts
> +import { TipoActa } from './tipo_acta';
Si es posible, sería crack que hubiera un archivo (`from`) por cada CRUD. Por ejemplo, para el [crud de terceros](https://github.com/udistrital/arka_cliente/blob/develop/src/app/@core/data/models/terceros.ts)

Lo anterior ayudaría a evitar varias interfaces/clases repetidas ([ejemplo](https://github.com/udistrital/arka_cliente/blob/cc8c7ad33e14822da9dd4e9f44f3f3667853ddef/src/app/%40core/data/models/catalogo/jerarquia.ts)) y a darle un contexto adicional...

2021-09-03 05:26 UTC, AlexFBP commented on src/app/@core/data/models/acta_recibido/acta_recibido.ts
> +    FechaCreacion: Date;
En general: Donde estén los campos base de la OAS (id, Activo, FechaCreacion y FechaModificacion), considerar extender la [clase `Base`](https://github.com/udistrital/arka_cliente/blob/develop/src/app/@core/data/models/base.ts)

2021-09-03 23:02 UTC, AlexFBP requested changes
En general, bien. Uno que otro cambio menor se comentó.

Adicional a los componentes que ya se simplificaron, el componente de registro podría (a futuro, si no se alcanza en este PR/Issue) también combinarse con el de edición (#708)

2021-09-04 00:16 UTC, ludwinggsanchez commented on src/app/@core/data/models/acta_recibido/acta_recibido.ts
> +import { TipoActa } from './tipo_acta';
Me parece, abramos un nuevo issue para hacer un refactor a todos los modelos

2021-09-04 00:17 UTC, ludwinggsanchez commented on src/app/@core/data/models/acta_recibido/acta_recibido.ts
> +    FechaCreacion: Date;
Considerarlo en un nuevo issue de refactor de modelos

2021-09-04 00:39 UTC, AlexFBP commented on src/app/@core/data/models/acta_recibido/acta_recibido.ts
> +    FechaCreacion: Date;
Hecho:
- #766

2021-09-04 00:54 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/ver-acta-recibido/ver-acta-recibido.component.html
> +                  <input type="text" placeholder="NIT o Razón social" class="form-control"
Done

2021-09-04 00:54 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/ver-acta-recibido/ver-acta-recibido.component.html
> +                                formControlName="Fecha_Factura" disabled readonly>
Done

2021-09-04 05:46 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
> +    this.Datos.Formulario2.forEach((soporte, index) => { Soportes.push(this.generarSoporte(soporte, index)); });
Done

2021-09-04 05:47 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
> +    historico.FechaModificacion = new Date();
Done

2021-09-04 06:05 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.html
> +                        {{'GLOBAL.Errores.ErrorMinLength' | translate : {NUM : '4'} }}</p>
Done

2021-09-04 06:05 UTC, ludwinggsanchez commented on src/app/pages/ajustes/lista-movimientos/lista-movimientos.component.ts
> +    this.actaRecibidoHelper.getAllActasRecibidoByEstado(['Asociada a Entrada']).subscribe(res => {
Revisémoslo en otro issue

2021-09-04 06:54 UTC, AlexFBP approved these changes

2021-09-04 07:15 UTC, AlexFBP commented on src/app/pages/ajustes/lista-movimientos/lista-movimientos.component.ts
> +    this.actaRecibidoHelper.getAllActasRecibidoByEstado(['Asociada a Entrada']).subscribe(res => {
Hecho - Agregado a #762

2021-09-04 07:15 UTC, AlexFBP commented on src/app/helpers/acta_recibido/actaRecibidoHelper.ts
> +    public getAllActasRecibidoByEstado(estados: [string]) {
Agregado a #762

2021-09-04 07:29 UTC, merged