Feature/multiples soportes
udistrital/arka_cliente pull request #771
Opened 2021-09-08 23:07 UTC by ludwinggsanchez

fix: Bug no se guardan múltiples soportes.
fix: Bug no se visualizan múltiples soportes de un mismo acta.

closes #763 #765, udistrital/acta_recibido_crud#60, udistrital/acta_recibido_crud#61

2021-09-09 21:12 UTC, AlexFBP requested changes
Se observó valor agregado en i18n

Una parte son comentarios menores como:
- Evitar usar las ternas indiscriminadamente
- Limpiar espacios en blanco, usar extensiones para no tener que hacerlo a mano

En otro PR / momento
- Validar el tamaño máximo de los archivos

Ajustes/Revisar (lo comentado en):
- `aprovechamientos.component.ts` (y otras entradas)
- `ver-acta-recibido-component.html`

2021-09-09 22:09 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
> +            url ? window.open(url) : null;
Done

2021-09-09 22:09 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.html
> +
Done

2021-09-09 22:10 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/ver-acta-recibido/ver-acta-recibido.component.html
> +        <nb-card *ngIf="totales && elementos && elementos.length > 1">
Se hizo basado en el ítem 5 de #691

2021-09-09 22:14 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/edicion-acta-recibido/edicion-acta-recibido.component.ts
> +    transaccion_.UltimoEstado.UbicacionId ? await this.getSedeDepencencia(transaccion_.UltimoEstado.UbicacionId) : null;
Done

2021-09-09 22:18 UTC, ludwinggsanchez commented on src/app/pages/acta-recibido/registro-acta-recibido/registro-acta-recibido.component.ts
> +  sizeSoporte: number = 5;
Se puede validar, por ahora está funcionando bien con 5 MB

2021-09-10 07:50 UTC, AlexFBP commented on src/app/pages/acta-recibido/ver-acta-recibido/ver-acta-recibido.component.html
> +        <nb-card *ngIf="totales && elementos && elementos.length > 1">
Por eso, no? `> 1` cubriría de 2 en adelante, incluyendo el 2...

2021-09-10 07:57 UTC, AlexFBP commented on src/app/pages/acta-recibido/ver-acta-recibido/ver-acta-recibido.component.html
> +        <nb-card *ngIf="totales && elementos && elementos.length > 1">
```suggestion
        <nb-card *ngIf="totales && elementos && elementos.length > 0">
```

2021-09-11 02:38 UTC, AlexFBP approved these changes

2021-09-11 02:39 UTC, merged