Bug cargar clases
udistrital/arka_cliente pull request #788
Opened 2021-09-20 07:56 UTC by ludwinggsanchez

Relacionado a #787

2021-09-20 13:23 UTC, AlexFBP requested changes

2021-09-20 13:23 UTC, AlexFBP commented on src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
> +          if (res2.length !== 0) {
Si hay la posibilidad de que `res2` no sea un arreglo (ej, cuando `res2 = null` o `res2 = undefined`), esto va a fallar...
Chequear primero que `res2` sea un arreglo

2021-09-20 13:23 UTC, AlexFBP commented on src/app/pages/catalogo-bienes/arbol/arbol.component.html
> -        </mat-tree-node>
Esta es la plantilla cuando estamos "en las hojas" (cuando no hay hijos), entiendo que se eliminó porque la otra plantilla, el otro caso (cuando hay hijos) ahora incluye/resuelve también este caso, si?

2021-09-20 13:55 UTC, AlexFBP commented on src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
> +          if (res2.length !== 0) {
(Alternativamente, garantizar que el `getDetalleSubgrupo` retorne siempre un arreglo...)

2021-09-21 00:36 UTC, ludwinggsanchez commented on src/app/pages/catalogo-bienes/arbol/arbol.component.html
> -        </mat-tree-node>
Corrrrecto

2021-09-21 00:38 UTC, ludwinggsanchez commented on src/app/pages/catalogo-bienes/registro-cuentas-catalogo/registro-cuentas-catalogo.component.ts
> +          if (res2.length !== 0) {
El cambio se hizo en [d571041](https://github.com/udistrital/catalogo_elementos_crud/pull/82/commits/d5710416a9a7e76259ebe76f6996ca9d6ee97650)

2021-09-23 00:34 UTC, AlexFBP approved these changes

2021-09-23 00:34 UTC, merged