Feature/tabla salidas
udistrital/arka_cliente pull request #836
Opened 2021-10-30 04:03 UTC by ludwinggsanchez

Relacionado con #711

2021-10-31 05:32 UTC, AlexFBP requested changes
En general bien. Uno que otro tema pequeño a revisar

2021-10-31 05:32 UTC, AlexFBP commented on src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.html
> +        <!-- <mat-paginator [pageSizeOptions]="[10, 20, 30, 40, 50]" (page)="cambioPagina($event)"></mat-paginator> -->
Eliminar o dejar comentado antes (en código) por qué se dejó comentado y/o cómo proceder al respecto
```suggestion
```

2021-10-31 05:32 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.html
>        <p></p>
Ver lo comentado en la L174 de src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.html. Si se puede quitar, mejor
```suggestion
```

2021-11-02 18:03 UTC, AlexFBP requested changes

2021-11-02 18:03 UTC, AlexFBP commented on src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
> +      const obs = 'Salida con elementos Devolutivos o de Consumo Controlado asignados a funcionario.';
Faltaría que este texto venga por i18n...

2021-11-02 18:03 UTC, AlexFBP commented on src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
> +    const obs = 'Salida con elementos de consumo asignados a funcionario.';
Este texto debería venir por i18n...

2021-11-02 18:03 UTC, AlexFBP commented on src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
>              (Swal as any).fire({
En donde se pueda, cambiar al `pUpManager`

2021-11-03 07:45 UTC, ludwinggsanchez commented on src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
> +      const obs = 'Salida con elementos Devolutivos o de Consumo Controlado asignados a funcionario.';
Es una observación que directamente se almacena directamente en base de datos, no es un label.

2021-11-03 07:45 UTC, ludwinggsanchez commented on src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
> +    const obs = 'Salida con elementos de consumo asignados a funcionario.';
Es una observación que directamente se almacena directamente en base de datos, no es un label.

2021-11-03 07:47 UTC, ludwinggsanchez commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.html
> -          <option value="sleccione un valor" selected disabled></option>
Es un completer, la opción vacía es pertinente cuando se trata de un select.

Interfaz actual:

![image](https://user-images.githubusercontent.com/35748918/140024555-d2c571ae-db8f-4e0a-bb29-409451d5d1bd.png)

2021-11-03 13:51 UTC, AlexFBP approved these changes

2021-11-03 13:51 UTC, merged