Feature/traslados
udistrital/arka_cliente pull request #846
Opened 2021-11-16 16:41 UTC by ludwinggsanchez

2021-11-17 16:37 UTC, AlexFBP requested changes

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +      this.form_salida.patchValue({ Ubicacion: '' });
Las líneas 84 y 99 no solo son iguales sino comunes a ambas ramas del `if`, probar si se dejan "factorizar", dejando una sola línea antes o después de todo el bloque `if`

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +        map(val => typeof val === 'string' ? val : this.muestraFuncionario(val)),
```suggestion
        map(val => (typeof val === 'string') ? val : this.muestraFuncionario(val)),
```

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +      const checkInvalidTercero = typeof (valor) === 'object' && !valor.Tercero ? true : false;
Uso innecesario de ternas, de hecho una terna funciona con un booleano por lo que lo que está a la izquierda ya sería un booleano
```suggestion
      const checkStringLength = typeof (valor) === 'string' && valor.length < 4 && valor !== '';
      const checkInvalidString = typeof (valor) === 'string' && valor !== '';
      const checkInvalidTercero = typeof (valor) === 'object' && !valor.Tercero;
```
Nota: Cuando se requiera negar, agrupar todo entre paréntesis y colocar el operador `!` al comienzo

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +        checkInvalidString || checkInvalidTercero ? { terceroNoValido: true } : null;
Una terna dentro de otra... Desambiguar/separar la lógica de cada terna (y hacerla legible) usando paréntesis, faltan...

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +      const checkInvalidObject = typeof (valor) === 'object' && !valor.Id ? true : false;
Uso innecesario de ternas
```suggestion
      const checkStringLength = typeof (valor) === 'string' && valor.length < 4 && valor !== '';
      const checkInvalidString = typeof (valor) === 'string' && valor !== '';
      const checkInvalidObject = typeof (valor) === 'object' && !valor.Id;
```
Nota: Cuando a futuro se requiera negar, agrupar todo entre paréntesis y colocar el operador `!` al comienzo

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +        checkInvalidString || checkInvalidObject ? { dependenciaNoValido: true } : null;
Una terna dentro de otra... Desambiguar/separar la lógica de cada terna (y hacerla legible) usando paréntesis, faltan...

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.html
> +            <mat-option value="">--{{ 'GLOBAL.seleccionar' | translate }}--</mat-option>
Ver lo comentado en la L56 de `src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.html`, posiblemente se pueda reutilizar

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.html
> +            <mat-option value="">--{{ 'GLOBAL.seleccionar' | translate }}--</mat-option>
Ver lo comentado en la L56 de `src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.html`, posiblemente se pueda reutilizar

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.ts
> +      this.formTraslado.get('ubicacion').patchValue({ ubicacion: '' });
La L162 se repite con la L147. Adicionalmente se observa que son comunes a ambas ramas del `if`, por lo que se podría "factorizar" dejando esa línea antes o después del bloque `if`. Revisar

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.ts
> +      const checkInvalidTercero = typeof (valor) === 'object' && !valor.Tercero ? true : false;
Uso innecesario de ternas
```suggestion
      const checkStringLength = typeof (valor) === 'string' && valor.length < 4 && valor !== '';
      const checkInvalidString = typeof (valor) === 'string' && valor !== '';
      const checkInvalidTercero = typeof (valor) === 'object' && !valor.Tercero;
```

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.ts
> +        checkInvalidString || checkInvalidTercero ? { terceroNoValido: true } : null;
Desambiguar la lógica de cada terna usando paréntesis

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.ts
> +      const checkInvalidObject = typeof (valor) === 'object' && !valor.Id ? true : false;
Uso innecesario de ternas
```suggestion
      const checkStringLength = typeof (valor) === 'string' && valor.length < 4 && valor !== '';
      const checkInvalidString = typeof (valor) === 'string' && valor !== '';
      const checkInvalidObject = typeof (valor) === 'object' && !valor.Id;
```

2021-11-17 16:37 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.ts
> +        checkInvalidString || checkInvalidObject ? { dependenciaNoValido: true } : null;
Desambiguar la lógica de cada terna usando paréntesis

2021-11-18 03:15 UTC, AlexFBP requested changes
En general, bien. Para finalizar, confirmar/revisar paréntesis faltantes en algunas ternas para facilitar la legibilidad...

2021-11-18 03:15 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +        (checkInvalidString || checkInvalidTercero) ? { terceroNoValido: true } : null;
Para confirmar/finalizar... toda esta línea sería "el `else` de la primer terna", si?
```suggestion
        ((checkInvalidString || checkInvalidTercero) ? { terceroNoValido: true } : null);
```

2021-11-18 03:15 UTC, AlexFBP commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
>          checkInvalidString || checkInvalidObject ? { dependenciaNoValido: true } : null;
Faltaría esto?
```suggestion
        ((checkInvalidString || checkInvalidObject) ? { dependenciaNoValido: true } : null);
```

2021-11-18 03:15 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.ts
> +        (checkInvalidString || checkInvalidTercero) ? { terceroNoValido: true } : null;
Confirmar/Revisar si...
```suggestion
        ((checkInvalidString || checkInvalidTercero) ? { terceroNoValido: true } : null);
```

2021-11-18 03:15 UTC, AlexFBP commented on src/app/pages/traslados/form-traslado/form-traslado.component.ts
> +        (checkInvalidString || checkInvalidObject) ? { dependenciaNoValido: true } : null;
Confirmar/Revisar si...
```suggestion
        ((checkInvalidString || checkInvalidObject) ? { dependenciaNoValido: true } : null);
```

2021-11-18 03:19 UTC, ludwinggsanchez commented on src/app/pages/salidas/form-elementos-seleccionados/form-elementos-seleccionados.component.ts
> +        (checkInvalidString || checkInvalidTercero) ? { terceroNoValido: true } : null;
Sería más como un else if, el else sería cuando no hay ningún error

2021-11-18 20:21 UTC, AlexFBP requested changes

2021-11-18 20:21 UTC, AlexFBP commented on src/app/@core/data/models/traslados/traslado.ts
> +}
Si esto es nuevo, y lo podemos agrupar-en/mover-a un único archivo .ts que tenga los modelos exclusivos del MID, mejor...

2021-11-18 20:21 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.html
> +  <div>
Evitar tags "vacíos", entre menos tags se usen desde un comienzo, mejor. Si más adelante se necesita algún tipo de directiva (`ng-if`, etc), probar primero si el `mat-card` (o el tag que aplique) la acepta
```suggestion
```
(ver comentario asociado en la L24)

2021-11-18 20:21 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.html
> +  </div>
De la mano con la L2
```suggestion
```

2021-11-18 20:21 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.ts
> +          title: 'Funcionario Destino',
Falta traer por i18n

2021-11-18 20:21 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.ts
> +          title: 'Funcionario Origen',
Falta traer por i18n

2021-11-18 20:21 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.ts
> +          title: 'Ubicacion',
Falta traer por i18n

2021-11-18 20:21 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.ts
> +          title: 'Consecutivo',
Falta traer por i18n

2021-11-18 20:21 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.ts
> +          title: 'Fecha de Creacion',
Falta traer por i18n

2021-11-19 17:15 UTC, AlexFBP requested changes
- Un comentario "menor", recomendado, respecto a src/app/helpers/traslados/trasladosHelper.ts; se sugiere, considerar mover el helper de traslados al de movimientos...

Los siguientes son requeridos, apoyarse en la vista [_Files Changed_](https://github.com/udistrital/arka_cliente/pull/846/files). Se marcaron como resueltos pero no se hizo nada al respecto...
- Faltan frases por tomar de i18n, en títulos, posiblemente sea solamente tomar keys ya existentes
- Falta confirmar/desambiguar la lógica de las ternas anidadas, **agregando paréntesis**, bien sea mediante la aceptación de los _suggested changes_ dejados, o manualmente agregandolos donde hagan falta - [Razón](https://stackoverflow.com/a/38410250/3180052)

2021-11-19 17:15 UTC, AlexFBP commented on src/app/helpers/traslados/trasladosHelper.ts
> +}
Considerar esto mejor dentro de movimientosHelper, teniendo en cuenta que el traslado se puede tratar como un tipo de movimiento...

2021-11-19 22:38 UTC, AlexFBP requested changes
Un par de ajustes menores y quedaría

2021-11-19 22:38 UTC, AlexFBP commented on src/app/pages/traslados/consulta-traslados/consulta-traslados.component.html
> +      <!-- <ngx-form-traslado *ngIf="modoCrud" [modo]="modoCrud"></ngx-form-traslado> -->
Eliminar
```suggestion
```
... o dejar comentado (en código, justo arriba) cómo proceder con esto

2021-11-19 22:38 UTC, AlexFBP commented on src/app/pages/traslados/registro-traslado/registro-traslado.component.ts
> +    (Swal as any).fire({
Cambiar por el `pUpmanager`

2021-11-23 06:09 UTC, AlexFBP requested changes

2021-11-23 06:12 UTC, AlexFBP approved these changes

2021-11-23 06:19 UTC, merged