Feature/bajas
udistrital/arka_cliente pull request #853
Opened 2021-11-30 02:46 UTC by ludwinggsanchez

Relacionado con #844

2021-12-01 00:17 UTC, AlexFBP requested changes

2021-12-01 00:17 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.html
> +              {{ 'GLOBAL.Nombre' | translate }}
Revisar repetidos
- `id="placa"` repetido en varios input, cada `id` debe ser único en un mismo documento html
- `{{ 'GLOBAL.Nombre' | translate }}` está repetido en varios de los campos...

2021-12-01 04:38 UTC, AlexFBP requested changes
En general bien. Un par de _suggested changes_ y quedaría

2021-12-01 04:38 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.html
> +</mat-vertical-stepper>
```suggestion
</mat-vertical-stepper>

```

2021-12-01 04:38 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
> +      return !elementos ? { errorNoElementos: true } : null;
![image](https://user-images.githubusercontent.com/6588872/144172436-3c549edf-6733-44c2-975c-c5242d44b294.png)
Es una bobada pero
```suggestion
      return elementos ? null : { errorNoElementos: true };
```

2021-12-05 06:18 UTC, AlexFBP requested changes

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
> +@Component({
(En general) Dejar las constantes en un mismo lado, o por lo menos al comienzo del archivo, antes de la declaración del componente. Por ejemplo para este archivo:

```suggestion
import { DocumentoService } from '../../../@core/data/documento.service';

const SIZE_SOPORTE = 5 * 1024000;

@Component({
```
Y ajustar las L27, L421 y L428 según sea adecuado

Lo anterior con el fin de
- Que las constantes queden en un mismo lado
- Que cuando se tengan que traer, bien sea de configuración API, de parametros API o de otro lado, "solo sea cambiarlas en un mismo lado"

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/consulta-bajas/consulta-bajas.component.ts
> +import Swal from 'sweetalert2';
Aprovechar el `pUpmanager`, si el día de mañana se abandona `Swal`, podríamos cambiarlo en un mismo lado, y haciendo las transformaciones necesarias pàra que funcione la nueva librería, en ese mismo lado

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/consulta-bajas/consulta-bajas.component.ts
> +    }
Pareciera que `this.modo` podría ser un candidato a `switch/case` ? Revisar si vale la pena cambiarlo...

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
> +  bajaId: number = 0;
Mover estas inicializaciones (con valores constantes, que no dependan de funciones) al `constructor`

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
> +    'funcionario', 'marca', 'sede', 'dependencia', 'ubicacion'];
Mover estas inicializaciones al `constructor`

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
> +  sizeSoporte: number = 5;
Ver comentario en las L15-16

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
> +        if (file.size < this.sizeSoporte * 1024000) {
Ver comentario en las L15-16

2021-12-05 06:18 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
> +            { SIZE: this.sizeSoporte }));
Ver comentario en las L15-16

2021-12-06 10:05 UTC, ludwinggsanchez commented on src/app/pages/bajas/consulta-bajas/consulta-bajas.component.ts
> +import Swal from 'sweetalert2';
Se está utilizando para las alertas con varios pasos como cuando se inserta la razón de rechazo, para lo demás se utiliza el `pUpanager`

2021-12-06 20:58 UTC, AlexFBP requested changes
Un cambio menor y quedaría...

2021-12-06 20:58 UTC, AlexFBP commented on src/app/pages/bajas/form-solicitud/form-solicitud.component.ts
>    sizeSoporte: number = 5;
Dado que ya se está haciendo en el `constructor`
```suggestion
  sizeSoporte: number;
```

2021-12-07 03:47 UTC, AlexFBP approved these changes

2021-12-07 03:47 UTC, merged