feat: Depreciacion
udistrital/arka_cliente pull request #878
Opened 2021-12-31 04:20 UTC by ludwinggsanchez

Relacionado con udistrital/arka_cliente#874

2021-12-31 13:31 UTC, AlexFBP requested changes
En general bien. Un cambio menor: Siempre que haya ternas anidadas, desambiguar la lógica agregando paréntesis

2021-12-31 13:31 UTC, AlexFBP commented on src/app/pages/salidas/tabla-elementos-asignados/tabla-elementos-asignados.component.ts
> +            (alertVidaUtil) ? 'GLOBAL.movimientos.alertaVida' : null;
Desambiguar lógica de la terna, agregando grupos de paréntesis por cada nivel de anidación

2022-01-03 11:37 UTC, ludwinggsanchez commented
Pendiente mejorar manejo de fechas

2022-01-03 12:10 UTC, AlexFBP approved these changes

2022-01-03 12:27 UTC, merged