Feature/comprobante contable
udistrital/arka_cliente pull request #883
Opened 2022-01-15 11:19 UTC by ludwinggsanchez

Relacionado con #584

2022-01-16 02:44 UTC, AlexFBP requested changes
En general, bien

Un par de cosas por revisar...

2022-01-17 05:10 UTC, ludwinggsanchez commented on src/app/pages/ajustes/comprobante/comprobante.component.ts
> +export const MVTO_CR = 345;
Se crea el helper aunque ya no se necesitan estos valores

2022-01-17 05:11 UTC, ludwinggsanchez commented on src/app/helpers/terceros/tercerosHelper.ts
> +            return this.rqManager.get(endpoint).pipe(
Dado que es un completer, el manejo de muchos resultados se hace exigiendo un número mínimo de caracteres

2022-01-17 05:49 UTC, AlexFBP approved these changes

2022-01-17 05:49 UTC, merged